kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: cluster-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
