apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: rhsso
    annotations:
      description: ConfigMap providing service ca bundle.
      openshift.io/generated-by: OpenShiftNewApp
      service.beta.openshift.io/inject-cabundle: "true"
    creationTimestamp: null
    labels:
      app: sso74-ocp4-x509-https
      app.kubernetes.io/component: sso74-ocp4-x509-https
      app.kubernetes.io/instance: sso74-ocp4-x509-https
      application: sso
      rhsso: 7.4.2.GA
      template: sso74-ocp4-x509-https
    name: sso-service-ca
- apiVersion: v1
  kind: Service
  metadata:
    namespace: rhsso
    annotations:
      description: The web server's https port.
      openshift.io/generated-by: OpenShiftNewApp
      service.alpha.openshift.io/serving-cert-secret-name: sso-x509-https-secret
    creationTimestamp: null
    labels:
      app: sso74-ocp4-x509-https
      app.kubernetes.io/component: sso74-ocp4-x509-https
      app.kubernetes.io/instance: sso74-ocp4-x509-https
      application: sso
      rhsso: 7.4.2.GA
      template: sso74-ocp4-x509-https
    name: sso
  spec:
    ports:
    - port: 8443
      targetPort: 8443
    selector:
      deploymentConfig: sso
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    namespace: rhsso
    annotations:
      description: The JGroups ping port for clustering.
      openshift.io/generated-by: OpenShiftNewApp
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
      service.alpha.openshift.io/serving-cert-secret-name: sso-x509-jgroups-secret
    creationTimestamp: null
    labels:
      app: sso74-ocp4-x509-https
      app.kubernetes.io/component: sso74-ocp4-x509-https
      app.kubernetes.io/instance: sso74-ocp4-x509-https
      application: sso
      rhsso: 7.4.2.GA
      template: sso74-ocp4-x509-https
    name: sso-ping
  spec:
    clusterIP: None
    ports:
    - name: ping
      port: 8888
      targetPort: 0
    selector:
      deploymentConfig: sso
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    namespace: rhsso
    annotations:
      description: Route for application's https service.
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: sso74-ocp4-x509-https
      app.kubernetes.io/component: sso74-ocp4-x509-https
      app.kubernetes.io/instance: sso74-ocp4-x509-https
      application: sso
      rhsso: 7.4.2.GA
      template: sso74-ocp4-x509-https
    name: sso
  spec:
    tls:
      termination: reencrypt
    to:
      kind: Service
      name: sso
      weight: null
  status: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    namespace: rhsso
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: sso74-ocp4-x509-https
      app.kubernetes.io/component: sso74-ocp4-x509-https
      app.kubernetes.io/instance: sso74-ocp4-x509-https
      application: sso
      rhsso: 7.4.2.GA
      template: sso74-ocp4-x509-https
    name: sso
  spec:
    replicas: 1
    selector:
      deploymentConfig: sso
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          application: sso
          deploymentConfig: sso
        name: sso
      spec:
        containers:
        - env:
          - name: SSO_HOSTNAME
          - name: DB_MIN_POOL_SIZE
          - name: DB_MAX_POOL_SIZE
          - name: DB_TX_ISOLATION
          - name: JGROUPS_PING_PROTOCOL
            value: openshift.DNS_PING
          - name: OPENSHIFT_DNS_PING_SERVICE_NAME
            value: sso-ping
          - name: OPENSHIFT_DNS_PING_SERVICE_PORT
            value: "8888"
          - name: X509_CA_BUNDLE
            value: /var/run/configmaps/service-ca/service-ca.crt /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          - name: JGROUPS_CLUSTER_PASSWORD
            value: mTeTjYMGOBtUGsXhNRA4H08cSMcn6vR1
          - name: SSO_ADMIN_USERNAME
            value: kwYU8O5R
          - name: SSO_ADMIN_PASSWORD
            value: PkiAgrq2qrNsxWpTPNviD1VWgQuioSTj
          - name: SSO_REALM
          - name: SSO_SERVICE_USERNAME
          - name: SSO_SERVICE_PASSWORD
          image: image-registry.openshift-image-registry.svc:5000/openshift/keycloak:rhssoxoracle
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/livenessProbe.sh
            initialDelaySeconds: 60
          name: sso
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/readinessProbe.sh
          resources:
            limits:
              memory: 1Gi
          volumeMounts:
          - mountPath: /etc/x509/https
            name: sso-x509-https-volume
            readOnly: true
          - mountPath: /etc/x509/jgroups
            name: sso-x509-jgroups-volume
            readOnly: true
          - mountPath: /var/run/configmaps/service-ca
            name: service-ca
            readOnly: true
        terminationGracePeriodSeconds: 75
        volumes:
        - name: sso-x509-https-volume
          secret:
            secretName: sso-x509-https-secret
        - name: sso-x509-jgroups-volume
          secret:
            secretName: sso-x509-jgroups-secret
        - configMap:
            name: sso-service-ca
          name: service-ca
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - sso
        from:
          kind: ImageStreamTag
          name: keycloak:rhssoxoracle
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
kind: List
metadata: {}
