apiVersion: v1
kind: ConfigMap
metadata:
    annotations:
      description: ConfigMap providing service ca bundle.
      openshift.io/generated-by: OpenShiftNewApp
      service.beta.openshift.io/inject-cabundle: "true"
    creationTimestamp: null
    labels:
      app: sso74-ocp4-x509-https
      app.kubernetes.io/component: sso74-ocp4-x509-https
      app.kubernetes.io/instance: sso74-ocp4-x509-https
      application: sso
      rhsso: 7.4.2.GA
      template: sso74-ocp4-x509-https
    name: sso-service-ca
